package com.doushabao.saas.pojo.order;

import java.util.Date;

public class Bill {

    /**
     * 未支付
     */
    public static Integer NO_PAY = 0;

    /**
     * 已审核
     */
    public static Integer CHECK_BILL = 1;

    /**
     * 支付成功
     */
    public static Integer PAY_SUCCESS = 2;

    /**
     * 结算失败
     */
    public static Integer PAY_FAILED = 3;

    /**
     * 删除账单
     */
    public static Integer DELETE_BILL = 4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill.id
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill.source
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill.ticket_no
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    private String ticketNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill.year
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill.month
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    private Integer month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill.add_time
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill.pay_time
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill.origin_amount
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    private Integer originAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill.discount_amount
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    private Integer discountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill.amount
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill.status
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill.type
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill.message
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill.create_at
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill.update_at
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill.id
     *
     * @return the value of t_bill.id
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill.id
     *
     * @param id the value for t_bill.id
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill.source
     *
     * @return the value of t_bill.source
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill.source
     *
     * @param source the value for t_bill.source
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill.ticket_no
     *
     * @return the value of t_bill.ticket_no
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public String getTicketNo() {
        return ticketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill.ticket_no
     *
     * @param ticketNo the value for t_bill.ticket_no
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public void setTicketNo(String ticketNo) {
        this.ticketNo = ticketNo == null ? null : ticketNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill.year
     *
     * @return the value of t_bill.year
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill.year
     *
     * @param year the value for t_bill.year
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill.month
     *
     * @return the value of t_bill.month
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill.month
     *
     * @param month the value for t_bill.month
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill.add_time
     *
     * @return the value of t_bill.add_time
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill.add_time
     *
     * @param addTime the value for t_bill.add_time
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill.pay_time
     *
     * @return the value of t_bill.pay_time
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill.pay_time
     *
     * @param payTime the value for t_bill.pay_time
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill.origin_amount
     *
     * @return the value of t_bill.origin_amount
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public Integer getOriginAmount() {
        return originAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill.origin_amount
     *
     * @param originAmount the value for t_bill.origin_amount
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public void setOriginAmount(Integer originAmount) {
        this.originAmount = originAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill.discount_amount
     *
     * @return the value of t_bill.discount_amount
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public Integer getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill.discount_amount
     *
     * @param discountAmount the value for t_bill.discount_amount
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public void setDiscountAmount(Integer discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill.amount
     *
     * @return the value of t_bill.amount
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill.amount
     *
     * @param amount the value for t_bill.amount
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill.status
     *
     * @return the value of t_bill.status
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill.status
     *
     * @param status the value for t_bill.status
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill.type
     *
     * @return the value of t_bill.type
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill.type
     *
     * @param type the value for t_bill.type
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill.message
     *
     * @return the value of t_bill.message
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill.message
     *
     * @param message the value for t_bill.message
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill.create_at
     *
     * @return the value of t_bill.create_at
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill.create_at
     *
     * @param createAt the value for t_bill.create_at
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill.update_at
     *
     * @return the value of t_bill.update_at
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill.update_at
     *
     * @param updateAt the value for t_bill.update_at
     *
     * @mbg.generated Mon Jun 04 17:15:12 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}