package com.doushabao.saas.pojo.order;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CompanyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public CompanyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCompanyRankIsNull() {
            addCriterion("company_rank is null");
            return (Criteria) this;
        }

        public Criteria andCompanyRankIsNotNull() {
            addCriterion("company_rank is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyRankEqualTo(Integer value) {
            addCriterion("company_rank =", value, "companyRank");
            return (Criteria) this;
        }

        public Criteria andCompanyRankNotEqualTo(Integer value) {
            addCriterion("company_rank <>", value, "companyRank");
            return (Criteria) this;
        }

        public Criteria andCompanyRankGreaterThan(Integer value) {
            addCriterion("company_rank >", value, "companyRank");
            return (Criteria) this;
        }

        public Criteria andCompanyRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_rank >=", value, "companyRank");
            return (Criteria) this;
        }

        public Criteria andCompanyRankLessThan(Integer value) {
            addCriterion("company_rank <", value, "companyRank");
            return (Criteria) this;
        }

        public Criteria andCompanyRankLessThanOrEqualTo(Integer value) {
            addCriterion("company_rank <=", value, "companyRank");
            return (Criteria) this;
        }

        public Criteria andCompanyRankIn(List<Integer> values) {
            addCriterion("company_rank in", values, "companyRank");
            return (Criteria) this;
        }

        public Criteria andCompanyRankNotIn(List<Integer> values) {
            addCriterion("company_rank not in", values, "companyRank");
            return (Criteria) this;
        }

        public Criteria andCompanyRankBetween(Integer value1, Integer value2) {
            addCriterion("company_rank between", value1, value2, "companyRank");
            return (Criteria) this;
        }

        public Criteria andCompanyRankNotBetween(Integer value1, Integer value2) {
            addCriterion("company_rank not between", value1, value2, "companyRank");
            return (Criteria) this;
        }

        public Criteria andCompanyKeyIsNull() {
            addCriterion("company_key is null");
            return (Criteria) this;
        }

        public Criteria andCompanyKeyIsNotNull() {
            addCriterion("company_key is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyKeyEqualTo(String value) {
            addCriterion("company_key =", value, "companyKey");
            return (Criteria) this;
        }

        public Criteria andCompanyKeyNotEqualTo(String value) {
            addCriterion("company_key <>", value, "companyKey");
            return (Criteria) this;
        }

        public Criteria andCompanyKeyGreaterThan(String value) {
            addCriterion("company_key >", value, "companyKey");
            return (Criteria) this;
        }

        public Criteria andCompanyKeyGreaterThanOrEqualTo(String value) {
            addCriterion("company_key >=", value, "companyKey");
            return (Criteria) this;
        }

        public Criteria andCompanyKeyLessThan(String value) {
            addCriterion("company_key <", value, "companyKey");
            return (Criteria) this;
        }

        public Criteria andCompanyKeyLessThanOrEqualTo(String value) {
            addCriterion("company_key <=", value, "companyKey");
            return (Criteria) this;
        }

        public Criteria andCompanyKeyLike(String value) {
            addCriterion("company_key like", value, "companyKey");
            return (Criteria) this;
        }

        public Criteria andCompanyKeyNotLike(String value) {
            addCriterion("company_key not like", value, "companyKey");
            return (Criteria) this;
        }

        public Criteria andCompanyKeyIn(List<String> values) {
            addCriterion("company_key in", values, "companyKey");
            return (Criteria) this;
        }

        public Criteria andCompanyKeyNotIn(List<String> values) {
            addCriterion("company_key not in", values, "companyKey");
            return (Criteria) this;
        }

        public Criteria andCompanyKeyBetween(String value1, String value2) {
            addCriterion("company_key between", value1, value2, "companyKey");
            return (Criteria) this;
        }

        public Criteria andCompanyKeyNotBetween(String value1, String value2) {
            addCriterion("company_key not between", value1, value2, "companyKey");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCompanyLicenseIsNull() {
            addCriterion("company_license is null");
            return (Criteria) this;
        }

        public Criteria andCompanyLicenseIsNotNull() {
            addCriterion("company_license is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyLicenseEqualTo(String value) {
            addCriterion("company_license =", value, "companyLicense");
            return (Criteria) this;
        }

        public Criteria andCompanyLicenseNotEqualTo(String value) {
            addCriterion("company_license <>", value, "companyLicense");
            return (Criteria) this;
        }

        public Criteria andCompanyLicenseGreaterThan(String value) {
            addCriterion("company_license >", value, "companyLicense");
            return (Criteria) this;
        }

        public Criteria andCompanyLicenseGreaterThanOrEqualTo(String value) {
            addCriterion("company_license >=", value, "companyLicense");
            return (Criteria) this;
        }

        public Criteria andCompanyLicenseLessThan(String value) {
            addCriterion("company_license <", value, "companyLicense");
            return (Criteria) this;
        }

        public Criteria andCompanyLicenseLessThanOrEqualTo(String value) {
            addCriterion("company_license <=", value, "companyLicense");
            return (Criteria) this;
        }

        public Criteria andCompanyLicenseLike(String value) {
            addCriterion("company_license like", value, "companyLicense");
            return (Criteria) this;
        }

        public Criteria andCompanyLicenseNotLike(String value) {
            addCriterion("company_license not like", value, "companyLicense");
            return (Criteria) this;
        }

        public Criteria andCompanyLicenseIn(List<String> values) {
            addCriterion("company_license in", values, "companyLicense");
            return (Criteria) this;
        }

        public Criteria andCompanyLicenseNotIn(List<String> values) {
            addCriterion("company_license not in", values, "companyLicense");
            return (Criteria) this;
        }

        public Criteria andCompanyLicenseBetween(String value1, String value2) {
            addCriterion("company_license between", value1, value2, "companyLicense");
            return (Criteria) this;
        }

        public Criteria andCompanyLicenseNotBetween(String value1, String value2) {
            addCriterion("company_license not between", value1, value2, "companyLicense");
            return (Criteria) this;
        }

        public Criteria andLicenseImgUrlIsNull() {
            addCriterion("license_img_url is null");
            return (Criteria) this;
        }

        public Criteria andLicenseImgUrlIsNotNull() {
            addCriterion("license_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andLicenseImgUrlEqualTo(String value) {
            addCriterion("license_img_url =", value, "licenseImgUrl");
            return (Criteria) this;
        }

        public Criteria andLicenseImgUrlNotEqualTo(String value) {
            addCriterion("license_img_url <>", value, "licenseImgUrl");
            return (Criteria) this;
        }

        public Criteria andLicenseImgUrlGreaterThan(String value) {
            addCriterion("license_img_url >", value, "licenseImgUrl");
            return (Criteria) this;
        }

        public Criteria andLicenseImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("license_img_url >=", value, "licenseImgUrl");
            return (Criteria) this;
        }

        public Criteria andLicenseImgUrlLessThan(String value) {
            addCriterion("license_img_url <", value, "licenseImgUrl");
            return (Criteria) this;
        }

        public Criteria andLicenseImgUrlLessThanOrEqualTo(String value) {
            addCriterion("license_img_url <=", value, "licenseImgUrl");
            return (Criteria) this;
        }

        public Criteria andLicenseImgUrlLike(String value) {
            addCriterion("license_img_url like", value, "licenseImgUrl");
            return (Criteria) this;
        }

        public Criteria andLicenseImgUrlNotLike(String value) {
            addCriterion("license_img_url not like", value, "licenseImgUrl");
            return (Criteria) this;
        }

        public Criteria andLicenseImgUrlIn(List<String> values) {
            addCriterion("license_img_url in", values, "licenseImgUrl");
            return (Criteria) this;
        }

        public Criteria andLicenseImgUrlNotIn(List<String> values) {
            addCriterion("license_img_url not in", values, "licenseImgUrl");
            return (Criteria) this;
        }

        public Criteria andLicenseImgUrlBetween(String value1, String value2) {
            addCriterion("license_img_url between", value1, value2, "licenseImgUrl");
            return (Criteria) this;
        }

        public Criteria andLicenseImgUrlNotBetween(String value1, String value2) {
            addCriterion("license_img_url not between", value1, value2, "licenseImgUrl");
            return (Criteria) this;
        }

        public Criteria andCompanyCountryIsNull() {
            addCriterion("company_country is null");
            return (Criteria) this;
        }

        public Criteria andCompanyCountryIsNotNull() {
            addCriterion("company_country is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyCountryEqualTo(String value) {
            addCriterion("company_country =", value, "companyCountry");
            return (Criteria) this;
        }

        public Criteria andCompanyCountryNotEqualTo(String value) {
            addCriterion("company_country <>", value, "companyCountry");
            return (Criteria) this;
        }

        public Criteria andCompanyCountryGreaterThan(String value) {
            addCriterion("company_country >", value, "companyCountry");
            return (Criteria) this;
        }

        public Criteria andCompanyCountryGreaterThanOrEqualTo(String value) {
            addCriterion("company_country >=", value, "companyCountry");
            return (Criteria) this;
        }

        public Criteria andCompanyCountryLessThan(String value) {
            addCriterion("company_country <", value, "companyCountry");
            return (Criteria) this;
        }

        public Criteria andCompanyCountryLessThanOrEqualTo(String value) {
            addCriterion("company_country <=", value, "companyCountry");
            return (Criteria) this;
        }

        public Criteria andCompanyCountryLike(String value) {
            addCriterion("company_country like", value, "companyCountry");
            return (Criteria) this;
        }

        public Criteria andCompanyCountryNotLike(String value) {
            addCriterion("company_country not like", value, "companyCountry");
            return (Criteria) this;
        }

        public Criteria andCompanyCountryIn(List<String> values) {
            addCriterion("company_country in", values, "companyCountry");
            return (Criteria) this;
        }

        public Criteria andCompanyCountryNotIn(List<String> values) {
            addCriterion("company_country not in", values, "companyCountry");
            return (Criteria) this;
        }

        public Criteria andCompanyCountryBetween(String value1, String value2) {
            addCriterion("company_country between", value1, value2, "companyCountry");
            return (Criteria) this;
        }

        public Criteria andCompanyCountryNotBetween(String value1, String value2) {
            addCriterion("company_country not between", value1, value2, "companyCountry");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressIsNull() {
            addCriterion("company_address is null");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressIsNotNull() {
            addCriterion("company_address is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressEqualTo(String value) {
            addCriterion("company_address =", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotEqualTo(String value) {
            addCriterion("company_address <>", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressGreaterThan(String value) {
            addCriterion("company_address >", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressGreaterThanOrEqualTo(String value) {
            addCriterion("company_address >=", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressLessThan(String value) {
            addCriterion("company_address <", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressLessThanOrEqualTo(String value) {
            addCriterion("company_address <=", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressLike(String value) {
            addCriterion("company_address like", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotLike(String value) {
            addCriterion("company_address not like", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressIn(List<String> values) {
            addCriterion("company_address in", values, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotIn(List<String> values) {
            addCriterion("company_address not in", values, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressBetween(String value1, String value2) {
            addCriterion("company_address between", value1, value2, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotBetween(String value1, String value2) {
            addCriterion("company_address not between", value1, value2, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanySiteIsNull() {
            addCriterion("company_site is null");
            return (Criteria) this;
        }

        public Criteria andCompanySiteIsNotNull() {
            addCriterion("company_site is not null");
            return (Criteria) this;
        }

        public Criteria andCompanySiteEqualTo(String value) {
            addCriterion("company_site =", value, "companySite");
            return (Criteria) this;
        }

        public Criteria andCompanySiteNotEqualTo(String value) {
            addCriterion("company_site <>", value, "companySite");
            return (Criteria) this;
        }

        public Criteria andCompanySiteGreaterThan(String value) {
            addCriterion("company_site >", value, "companySite");
            return (Criteria) this;
        }

        public Criteria andCompanySiteGreaterThanOrEqualTo(String value) {
            addCriterion("company_site >=", value, "companySite");
            return (Criteria) this;
        }

        public Criteria andCompanySiteLessThan(String value) {
            addCriterion("company_site <", value, "companySite");
            return (Criteria) this;
        }

        public Criteria andCompanySiteLessThanOrEqualTo(String value) {
            addCriterion("company_site <=", value, "companySite");
            return (Criteria) this;
        }

        public Criteria andCompanySiteLike(String value) {
            addCriterion("company_site like", value, "companySite");
            return (Criteria) this;
        }

        public Criteria andCompanySiteNotLike(String value) {
            addCriterion("company_site not like", value, "companySite");
            return (Criteria) this;
        }

        public Criteria andCompanySiteIn(List<String> values) {
            addCriterion("company_site in", values, "companySite");
            return (Criteria) this;
        }

        public Criteria andCompanySiteNotIn(List<String> values) {
            addCriterion("company_site not in", values, "companySite");
            return (Criteria) this;
        }

        public Criteria andCompanySiteBetween(String value1, String value2) {
            addCriterion("company_site between", value1, value2, "companySite");
            return (Criteria) this;
        }

        public Criteria andCompanySiteNotBetween(String value1, String value2) {
            addCriterion("company_site not between", value1, value2, "companySite");
            return (Criteria) this;
        }

        public Criteria andCompanyScopeIsNull() {
            addCriterion("company_scope is null");
            return (Criteria) this;
        }

        public Criteria andCompanyScopeIsNotNull() {
            addCriterion("company_scope is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyScopeEqualTo(String value) {
            addCriterion("company_scope =", value, "companyScope");
            return (Criteria) this;
        }

        public Criteria andCompanyScopeNotEqualTo(String value) {
            addCriterion("company_scope <>", value, "companyScope");
            return (Criteria) this;
        }

        public Criteria andCompanyScopeGreaterThan(String value) {
            addCriterion("company_scope >", value, "companyScope");
            return (Criteria) this;
        }

        public Criteria andCompanyScopeGreaterThanOrEqualTo(String value) {
            addCriterion("company_scope >=", value, "companyScope");
            return (Criteria) this;
        }

        public Criteria andCompanyScopeLessThan(String value) {
            addCriterion("company_scope <", value, "companyScope");
            return (Criteria) this;
        }

        public Criteria andCompanyScopeLessThanOrEqualTo(String value) {
            addCriterion("company_scope <=", value, "companyScope");
            return (Criteria) this;
        }

        public Criteria andCompanyScopeLike(String value) {
            addCriterion("company_scope like", value, "companyScope");
            return (Criteria) this;
        }

        public Criteria andCompanyScopeNotLike(String value) {
            addCriterion("company_scope not like", value, "companyScope");
            return (Criteria) this;
        }

        public Criteria andCompanyScopeIn(List<String> values) {
            addCriterion("company_scope in", values, "companyScope");
            return (Criteria) this;
        }

        public Criteria andCompanyScopeNotIn(List<String> values) {
            addCriterion("company_scope not in", values, "companyScope");
            return (Criteria) this;
        }

        public Criteria andCompanyScopeBetween(String value1, String value2) {
            addCriterion("company_scope between", value1, value2, "companyScope");
            return (Criteria) this;
        }

        public Criteria andCompanyScopeNotBetween(String value1, String value2) {
            addCriterion("company_scope not between", value1, value2, "companyScope");
            return (Criteria) this;
        }

        public Criteria andMainLineIsNull() {
            addCriterion("main_line is null");
            return (Criteria) this;
        }

        public Criteria andMainLineIsNotNull() {
            addCriterion("main_line is not null");
            return (Criteria) this;
        }

        public Criteria andMainLineEqualTo(String value) {
            addCriterion("main_line =", value, "mainLine");
            return (Criteria) this;
        }

        public Criteria andMainLineNotEqualTo(String value) {
            addCriterion("main_line <>", value, "mainLine");
            return (Criteria) this;
        }

        public Criteria andMainLineGreaterThan(String value) {
            addCriterion("main_line >", value, "mainLine");
            return (Criteria) this;
        }

        public Criteria andMainLineGreaterThanOrEqualTo(String value) {
            addCriterion("main_line >=", value, "mainLine");
            return (Criteria) this;
        }

        public Criteria andMainLineLessThan(String value) {
            addCriterion("main_line <", value, "mainLine");
            return (Criteria) this;
        }

        public Criteria andMainLineLessThanOrEqualTo(String value) {
            addCriterion("main_line <=", value, "mainLine");
            return (Criteria) this;
        }

        public Criteria andMainLineLike(String value) {
            addCriterion("main_line like", value, "mainLine");
            return (Criteria) this;
        }

        public Criteria andMainLineNotLike(String value) {
            addCriterion("main_line not like", value, "mainLine");
            return (Criteria) this;
        }

        public Criteria andMainLineIn(List<String> values) {
            addCriterion("main_line in", values, "mainLine");
            return (Criteria) this;
        }

        public Criteria andMainLineNotIn(List<String> values) {
            addCriterion("main_line not in", values, "mainLine");
            return (Criteria) this;
        }

        public Criteria andMainLineBetween(String value1, String value2) {
            addCriterion("main_line between", value1, value2, "mainLine");
            return (Criteria) this;
        }

        public Criteria andMainLineNotBetween(String value1, String value2) {
            addCriterion("main_line not between", value1, value2, "mainLine");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIsNull() {
            addCriterion("business_name is null");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIsNotNull() {
            addCriterion("business_name is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessNameEqualTo(String value) {
            addCriterion("business_name =", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotEqualTo(String value) {
            addCriterion("business_name <>", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameGreaterThan(String value) {
            addCriterion("business_name >", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameGreaterThanOrEqualTo(String value) {
            addCriterion("business_name >=", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLessThan(String value) {
            addCriterion("business_name <", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLessThanOrEqualTo(String value) {
            addCriterion("business_name <=", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLike(String value) {
            addCriterion("business_name like", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotLike(String value) {
            addCriterion("business_name not like", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIn(List<String> values) {
            addCriterion("business_name in", values, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotIn(List<String> values) {
            addCriterion("business_name not in", values, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameBetween(String value1, String value2) {
            addCriterion("business_name between", value1, value2, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotBetween(String value1, String value2) {
            addCriterion("business_name not between", value1, value2, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessPhoneIsNull() {
            addCriterion("business_phone is null");
            return (Criteria) this;
        }

        public Criteria andBusinessPhoneIsNotNull() {
            addCriterion("business_phone is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessPhoneEqualTo(String value) {
            addCriterion("business_phone =", value, "businessPhone");
            return (Criteria) this;
        }

        public Criteria andBusinessPhoneNotEqualTo(String value) {
            addCriterion("business_phone <>", value, "businessPhone");
            return (Criteria) this;
        }

        public Criteria andBusinessPhoneGreaterThan(String value) {
            addCriterion("business_phone >", value, "businessPhone");
            return (Criteria) this;
        }

        public Criteria andBusinessPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("business_phone >=", value, "businessPhone");
            return (Criteria) this;
        }

        public Criteria andBusinessPhoneLessThan(String value) {
            addCriterion("business_phone <", value, "businessPhone");
            return (Criteria) this;
        }

        public Criteria andBusinessPhoneLessThanOrEqualTo(String value) {
            addCriterion("business_phone <=", value, "businessPhone");
            return (Criteria) this;
        }

        public Criteria andBusinessPhoneLike(String value) {
            addCriterion("business_phone like", value, "businessPhone");
            return (Criteria) this;
        }

        public Criteria andBusinessPhoneNotLike(String value) {
            addCriterion("business_phone not like", value, "businessPhone");
            return (Criteria) this;
        }

        public Criteria andBusinessPhoneIn(List<String> values) {
            addCriterion("business_phone in", values, "businessPhone");
            return (Criteria) this;
        }

        public Criteria andBusinessPhoneNotIn(List<String> values) {
            addCriterion("business_phone not in", values, "businessPhone");
            return (Criteria) this;
        }

        public Criteria andBusinessPhoneBetween(String value1, String value2) {
            addCriterion("business_phone between", value1, value2, "businessPhone");
            return (Criteria) this;
        }

        public Criteria andBusinessPhoneNotBetween(String value1, String value2) {
            addCriterion("business_phone not between", value1, value2, "businessPhone");
            return (Criteria) this;
        }

        public Criteria andBusinessEmailIsNull() {
            addCriterion("business_email is null");
            return (Criteria) this;
        }

        public Criteria andBusinessEmailIsNotNull() {
            addCriterion("business_email is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessEmailEqualTo(String value) {
            addCriterion("business_email =", value, "businessEmail");
            return (Criteria) this;
        }

        public Criteria andBusinessEmailNotEqualTo(String value) {
            addCriterion("business_email <>", value, "businessEmail");
            return (Criteria) this;
        }

        public Criteria andBusinessEmailGreaterThan(String value) {
            addCriterion("business_email >", value, "businessEmail");
            return (Criteria) this;
        }

        public Criteria andBusinessEmailGreaterThanOrEqualTo(String value) {
            addCriterion("business_email >=", value, "businessEmail");
            return (Criteria) this;
        }

        public Criteria andBusinessEmailLessThan(String value) {
            addCriterion("business_email <", value, "businessEmail");
            return (Criteria) this;
        }

        public Criteria andBusinessEmailLessThanOrEqualTo(String value) {
            addCriterion("business_email <=", value, "businessEmail");
            return (Criteria) this;
        }

        public Criteria andBusinessEmailLike(String value) {
            addCriterion("business_email like", value, "businessEmail");
            return (Criteria) this;
        }

        public Criteria andBusinessEmailNotLike(String value) {
            addCriterion("business_email not like", value, "businessEmail");
            return (Criteria) this;
        }

        public Criteria andBusinessEmailIn(List<String> values) {
            addCriterion("business_email in", values, "businessEmail");
            return (Criteria) this;
        }

        public Criteria andBusinessEmailNotIn(List<String> values) {
            addCriterion("business_email not in", values, "businessEmail");
            return (Criteria) this;
        }

        public Criteria andBusinessEmailBetween(String value1, String value2) {
            addCriterion("business_email between", value1, value2, "businessEmail");
            return (Criteria) this;
        }

        public Criteria andBusinessEmailNotBetween(String value1, String value2) {
            addCriterion("business_email not between", value1, value2, "businessEmail");
            return (Criteria) this;
        }

        public Criteria andBusinessWxIsNull() {
            addCriterion("business_wx is null");
            return (Criteria) this;
        }

        public Criteria andBusinessWxIsNotNull() {
            addCriterion("business_wx is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessWxEqualTo(String value) {
            addCriterion("business_wx =", value, "businessWx");
            return (Criteria) this;
        }

        public Criteria andBusinessWxNotEqualTo(String value) {
            addCriterion("business_wx <>", value, "businessWx");
            return (Criteria) this;
        }

        public Criteria andBusinessWxGreaterThan(String value) {
            addCriterion("business_wx >", value, "businessWx");
            return (Criteria) this;
        }

        public Criteria andBusinessWxGreaterThanOrEqualTo(String value) {
            addCriterion("business_wx >=", value, "businessWx");
            return (Criteria) this;
        }

        public Criteria andBusinessWxLessThan(String value) {
            addCriterion("business_wx <", value, "businessWx");
            return (Criteria) this;
        }

        public Criteria andBusinessWxLessThanOrEqualTo(String value) {
            addCriterion("business_wx <=", value, "businessWx");
            return (Criteria) this;
        }

        public Criteria andBusinessWxLike(String value) {
            addCriterion("business_wx like", value, "businessWx");
            return (Criteria) this;
        }

        public Criteria andBusinessWxNotLike(String value) {
            addCriterion("business_wx not like", value, "businessWx");
            return (Criteria) this;
        }

        public Criteria andBusinessWxIn(List<String> values) {
            addCriterion("business_wx in", values, "businessWx");
            return (Criteria) this;
        }

        public Criteria andBusinessWxNotIn(List<String> values) {
            addCriterion("business_wx not in", values, "businessWx");
            return (Criteria) this;
        }

        public Criteria andBusinessWxBetween(String value1, String value2) {
            addCriterion("business_wx between", value1, value2, "businessWx");
            return (Criteria) this;
        }

        public Criteria andBusinessWxNotBetween(String value1, String value2) {
            addCriterion("business_wx not between", value1, value2, "businessWx");
            return (Criteria) this;
        }

        public Criteria andQrcodeIsNull() {
            addCriterion("QRCode is null");
            return (Criteria) this;
        }

        public Criteria andQrcodeIsNotNull() {
            addCriterion("QRCode is not null");
            return (Criteria) this;
        }

        public Criteria andQrcodeEqualTo(String value) {
            addCriterion("QRCode =", value, "qrcode");
            return (Criteria) this;
        }

        public Criteria andQrcodeNotEqualTo(String value) {
            addCriterion("QRCode <>", value, "qrcode");
            return (Criteria) this;
        }

        public Criteria andQrcodeGreaterThan(String value) {
            addCriterion("QRCode >", value, "qrcode");
            return (Criteria) this;
        }

        public Criteria andQrcodeGreaterThanOrEqualTo(String value) {
            addCriterion("QRCode >=", value, "qrcode");
            return (Criteria) this;
        }

        public Criteria andQrcodeLessThan(String value) {
            addCriterion("QRCode <", value, "qrcode");
            return (Criteria) this;
        }

        public Criteria andQrcodeLessThanOrEqualTo(String value) {
            addCriterion("QRCode <=", value, "qrcode");
            return (Criteria) this;
        }

        public Criteria andQrcodeLike(String value) {
            addCriterion("QRCode like", value, "qrcode");
            return (Criteria) this;
        }

        public Criteria andQrcodeNotLike(String value) {
            addCriterion("QRCode not like", value, "qrcode");
            return (Criteria) this;
        }

        public Criteria andQrcodeIn(List<String> values) {
            addCriterion("QRCode in", values, "qrcode");
            return (Criteria) this;
        }

        public Criteria andQrcodeNotIn(List<String> values) {
            addCriterion("QRCode not in", values, "qrcode");
            return (Criteria) this;
        }

        public Criteria andQrcodeBetween(String value1, String value2) {
            addCriterion("QRCode between", value1, value2, "qrcode");
            return (Criteria) this;
        }

        public Criteria andQrcodeNotBetween(String value1, String value2) {
            addCriterion("QRCode not between", value1, value2, "qrcode");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("create_at is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("create_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(Date value) {
            addCriterion("create_at =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(Date value) {
            addCriterion("create_at <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(Date value) {
            addCriterion("create_at >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("create_at >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(Date value) {
            addCriterion("create_at <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(Date value) {
            addCriterion("create_at <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<Date> values) {
            addCriterion("create_at in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<Date> values) {
            addCriterion("create_at not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(Date value1, Date value2) {
            addCriterion("create_at between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(Date value1, Date value2) {
            addCriterion("create_at not between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNull() {
            addCriterion("update_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNotNull() {
            addCriterion("update_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtEqualTo(Date value) {
            addCriterion("update_at =", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotEqualTo(Date value) {
            addCriterion("update_at <>", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThan(Date value) {
            addCriterion("update_at >", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("update_at >=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThan(Date value) {
            addCriterion("update_at <", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThanOrEqualTo(Date value) {
            addCriterion("update_at <=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIn(List<Date> values) {
            addCriterion("update_at in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotIn(List<Date> values) {
            addCriterion("update_at not in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtBetween(Date value1, Date value2) {
            addCriterion("update_at between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotBetween(Date value1, Date value2) {
            addCriterion("update_at not between", value1, value2, "updateAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_company
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 04 11:04:34 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_company
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}