package com.doushabao.saas.pojo.order;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ticket_no
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String ticketNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.product_id_list
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String productIdList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.original_amount
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Integer originalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.discount_amount
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Integer discountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_time
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_time
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.source
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.name
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.phone_no
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id_card
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.sex
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.currency
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.is_exit
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Integer isExit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_way
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Integer orderWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.excel_batch
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String excelBatch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.express_no
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String expressNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.purchas_order_no
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String purchasOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.goods_value
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Integer goodsValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.goods_value_detail
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String goodsValueDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.goods_category
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String goodsCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.goods_kind
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String goodsKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.goods_weight
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Double goodsWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.is_Reinforce
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Integer isReinforce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.prescription
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String prescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.express_mark
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String expressMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.express_time
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Date expressTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.express_line
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String expressLine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.express_channel
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String expressChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.receiver_address
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String receiverAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.loading_port
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String loadingPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.destination_port
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String destinationPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.border_shopping_site
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String borderShoppingSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.shopping_site
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String shoppingSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.shopping_time
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Date shoppingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.premium
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Integer premium;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_at
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.update_at
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ticket_no
     *
     * @return the value of t_order.ticket_no
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getTicketNo() {
        return ticketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ticket_no
     *
     * @param ticketNo the value for t_order.ticket_no
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setTicketNo(String ticketNo) {
        this.ticketNo = ticketNo == null ? null : ticketNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.product_id_list
     *
     * @return the value of t_order.product_id_list
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getProductIdList() {
        return productIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.product_id_list
     *
     * @param productIdList the value for t_order.product_id_list
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setProductIdList(String productIdList) {
        this.productIdList = productIdList == null ? null : productIdList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status
     *
     * @return the value of t_order.status
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.status
     *
     * @param status the value for t_order.status
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.original_amount
     *
     * @return the value of t_order.original_amount
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Integer getOriginalAmount() {
        return originalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.original_amount
     *
     * @param originalAmount the value for t_order.original_amount
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setOriginalAmount(Integer originalAmount) {
        this.originalAmount = originalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.discount_amount
     *
     * @return the value of t_order.discount_amount
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Integer getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.discount_amount
     *
     * @param discountAmount the value for t_order.discount_amount
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setDiscountAmount(Integer discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_time
     *
     * @return the value of t_order.order_time
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_time
     *
     * @param orderTime the value for t_order.order_time
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_time
     *
     * @return the value of t_order.pay_time
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_time
     *
     * @param payTime the value for t_order.pay_time
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.source
     *
     * @return the value of t_order.source
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.source
     *
     * @param source the value for t_order.source
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_id
     *
     * @return the value of t_order.user_id
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_id
     *
     * @param userId the value for t_order.user_id
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.name
     *
     * @return the value of t_order.name
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.name
     *
     * @param name the value for t_order.name
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.phone_no
     *
     * @return the value of t_order.phone_no
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.phone_no
     *
     * @param phoneNo the value for t_order.phone_no
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id_card
     *
     * @return the value of t_order.id_card
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id_card
     *
     * @param idCard the value for t_order.id_card
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.sex
     *
     * @return the value of t_order.sex
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.sex
     *
     * @param sex the value for t_order.sex
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.currency
     *
     * @return the value of t_order.currency
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.currency
     *
     * @param currency the value for t_order.currency
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.is_exit
     *
     * @return the value of t_order.is_exit
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Integer getIsExit() {
        return isExit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.is_exit
     *
     * @param isExit the value for t_order.is_exit
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setIsExit(Integer isExit) {
        this.isExit = isExit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_way
     *
     * @return the value of t_order.order_way
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Integer getOrderWay() {
        return orderWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_way
     *
     * @param orderWay the value for t_order.order_way
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setOrderWay(Integer orderWay) {
        this.orderWay = orderWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.excel_batch
     *
     * @return the value of t_order.excel_batch
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getExcelBatch() {
        return excelBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.excel_batch
     *
     * @param excelBatch the value for t_order.excel_batch
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setExcelBatch(String excelBatch) {
        this.excelBatch = excelBatch == null ? null : excelBatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.express_no
     *
     * @return the value of t_order.express_no
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getExpressNo() {
        return expressNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.express_no
     *
     * @param expressNo the value for t_order.express_no
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setExpressNo(String expressNo) {
        this.expressNo = expressNo == null ? null : expressNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.purchas_order_no
     *
     * @return the value of t_order.purchas_order_no
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getPurchasOrderNo() {
        return purchasOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.purchas_order_no
     *
     * @param purchasOrderNo the value for t_order.purchas_order_no
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setPurchasOrderNo(String purchasOrderNo) {
        this.purchasOrderNo = purchasOrderNo == null ? null : purchasOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.goods_value
     *
     * @return the value of t_order.goods_value
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Integer getGoodsValue() {
        return goodsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.goods_value
     *
     * @param goodsValue the value for t_order.goods_value
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setGoodsValue(Integer goodsValue) {
        this.goodsValue = goodsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.goods_value_detail
     *
     * @return the value of t_order.goods_value_detail
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getGoodsValueDetail() {
        return goodsValueDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.goods_value_detail
     *
     * @param goodsValueDetail the value for t_order.goods_value_detail
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setGoodsValueDetail(String goodsValueDetail) {
        this.goodsValueDetail = goodsValueDetail == null ? null : goodsValueDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.goods_category
     *
     * @return the value of t_order.goods_category
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getGoodsCategory() {
        return goodsCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.goods_category
     *
     * @param goodsCategory the value for t_order.goods_category
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setGoodsCategory(String goodsCategory) {
        this.goodsCategory = goodsCategory == null ? null : goodsCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.goods_kind
     *
     * @return the value of t_order.goods_kind
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getGoodsKind() {
        return goodsKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.goods_kind
     *
     * @param goodsKind the value for t_order.goods_kind
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setGoodsKind(String goodsKind) {
        this.goodsKind = goodsKind == null ? null : goodsKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.goods_weight
     *
     * @return the value of t_order.goods_weight
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Double getGoodsWeight() {
        return goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.goods_weight
     *
     * @param goodsWeight the value for t_order.goods_weight
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setGoodsWeight(Double goodsWeight) {
        this.goodsWeight = goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.is_Reinforce
     *
     * @return the value of t_order.is_Reinforce
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Integer getIsReinforce() {
        return isReinforce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.is_Reinforce
     *
     * @param isReinforce the value for t_order.is_Reinforce
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setIsReinforce(Integer isReinforce) {
        this.isReinforce = isReinforce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.prescription
     *
     * @return the value of t_order.prescription
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getPrescription() {
        return prescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.prescription
     *
     * @param prescription the value for t_order.prescription
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setPrescription(String prescription) {
        this.prescription = prescription == null ? null : prescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.express_mark
     *
     * @return the value of t_order.express_mark
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getExpressMark() {
        return expressMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.express_mark
     *
     * @param expressMark the value for t_order.express_mark
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setExpressMark(String expressMark) {
        this.expressMark = expressMark == null ? null : expressMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.express_time
     *
     * @return the value of t_order.express_time
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Date getExpressTime() {
        return expressTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.express_time
     *
     * @param expressTime the value for t_order.express_time
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setExpressTime(Date expressTime) {
        this.expressTime = expressTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.express_line
     *
     * @return the value of t_order.express_line
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getExpressLine() {
        return expressLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.express_line
     *
     * @param expressLine the value for t_order.express_line
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setExpressLine(String expressLine) {
        this.expressLine = expressLine == null ? null : expressLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.express_channel
     *
     * @return the value of t_order.express_channel
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getExpressChannel() {
        return expressChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.express_channel
     *
     * @param expressChannel the value for t_order.express_channel
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setExpressChannel(String expressChannel) {
        this.expressChannel = expressChannel == null ? null : expressChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.receiver_address
     *
     * @return the value of t_order.receiver_address
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.receiver_address
     *
     * @param receiverAddress the value for t_order.receiver_address
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.loading_port
     *
     * @return the value of t_order.loading_port
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getLoadingPort() {
        return loadingPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.loading_port
     *
     * @param loadingPort the value for t_order.loading_port
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setLoadingPort(String loadingPort) {
        this.loadingPort = loadingPort == null ? null : loadingPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.destination_port
     *
     * @return the value of t_order.destination_port
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getDestinationPort() {
        return destinationPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.destination_port
     *
     * @param destinationPort the value for t_order.destination_port
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setDestinationPort(String destinationPort) {
        this.destinationPort = destinationPort == null ? null : destinationPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.border_shopping_site
     *
     * @return the value of t_order.border_shopping_site
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getBorderShoppingSite() {
        return borderShoppingSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.border_shopping_site
     *
     * @param borderShoppingSite the value for t_order.border_shopping_site
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setBorderShoppingSite(String borderShoppingSite) {
        this.borderShoppingSite = borderShoppingSite == null ? null : borderShoppingSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.shopping_site
     *
     * @return the value of t_order.shopping_site
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getShoppingSite() {
        return shoppingSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.shopping_site
     *
     * @param shoppingSite the value for t_order.shopping_site
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setShoppingSite(String shoppingSite) {
        this.shoppingSite = shoppingSite == null ? null : shoppingSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.shopping_time
     *
     * @return the value of t_order.shopping_time
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Date getShoppingTime() {
        return shoppingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.shopping_time
     *
     * @param shoppingTime the value for t_order.shopping_time
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setShoppingTime(Date shoppingTime) {
        this.shoppingTime = shoppingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.premium
     *
     * @return the value of t_order.premium
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Integer getPremium() {
        return premium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.premium
     *
     * @param premium the value for t_order.premium
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setPremium(Integer premium) {
        this.premium = premium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_at
     *
     * @return the value of t_order.create_at
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.create_at
     *
     * @param createAt the value for t_order.create_at
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.update_at
     *
     * @return the value of t_order.update_at
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.update_at
     *
     * @param updateAt the value for t_order.update_at
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}