package com.doushabao.saas.pojo.order;

import java.util.Date;

public class WxPayLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_log.id
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_log.bill_id
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Long billId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_log.ticket_no
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String ticketNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_log.return_code
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String returnCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_log.return_msg
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String returnMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_log.code_url
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String codeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_log.prepay_id
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private String prepayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_log.create_at
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_log.update_at
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_log.id
     *
     * @return the value of t_wx_pay_log.id
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_log.id
     *
     * @param id the value for t_wx_pay_log.id
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_log.bill_id
     *
     * @return the value of t_wx_pay_log.bill_id
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Long getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_log.bill_id
     *
     * @param billId the value for t_wx_pay_log.bill_id
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setBillId(Long billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_log.ticket_no
     *
     * @return the value of t_wx_pay_log.ticket_no
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getTicketNo() {
        return ticketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_log.ticket_no
     *
     * @param ticketNo the value for t_wx_pay_log.ticket_no
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setTicketNo(String ticketNo) {
        this.ticketNo = ticketNo == null ? null : ticketNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_log.return_code
     *
     * @return the value of t_wx_pay_log.return_code
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_log.return_code
     *
     * @param returnCode the value for t_wx_pay_log.return_code
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode == null ? null : returnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_log.return_msg
     *
     * @return the value of t_wx_pay_log.return_msg
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getReturnMsg() {
        return returnMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_log.return_msg
     *
     * @param returnMsg the value for t_wx_pay_log.return_msg
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setReturnMsg(String returnMsg) {
        this.returnMsg = returnMsg == null ? null : returnMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_log.code_url
     *
     * @return the value of t_wx_pay_log.code_url
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getCodeUrl() {
        return codeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_log.code_url
     *
     * @param codeUrl the value for t_wx_pay_log.code_url
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setCodeUrl(String codeUrl) {
        this.codeUrl = codeUrl == null ? null : codeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_log.prepay_id
     *
     * @return the value of t_wx_pay_log.prepay_id
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public String getPrepayId() {
        return prepayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_log.prepay_id
     *
     * @param prepayId the value for t_wx_pay_log.prepay_id
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setPrepayId(String prepayId) {
        this.prepayId = prepayId == null ? null : prepayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_log.create_at
     *
     * @return the value of t_wx_pay_log.create_at
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_log.create_at
     *
     * @param createAt the value for t_wx_pay_log.create_at
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_log.update_at
     *
     * @return the value of t_wx_pay_log.update_at
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_log.update_at
     *
     * @param updateAt the value for t_wx_pay_log.update_at
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}