package com.doushabao.saas.pojo.product;

import java.math.BigDecimal;
import java.util.Date;

public class ProductStepPrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_step_price.id
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_step_price.product_id
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_step_price.month_order_sum
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    private Integer monthOrderSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_step_price.price
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_step_price.type
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_step_price.create_at
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_step_price.update_at
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_step_price.id
     *
     * @return the value of t_product_step_price.id
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_step_price.id
     *
     * @param id the value for t_product_step_price.id
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_step_price.product_id
     *
     * @return the value of t_product_step_price.product_id
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_step_price.product_id
     *
     * @param productId the value for t_product_step_price.product_id
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_step_price.month_order_sum
     *
     * @return the value of t_product_step_price.month_order_sum
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    public Integer getMonthOrderSum() {
        return monthOrderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_step_price.month_order_sum
     *
     * @param monthOrderSum the value for t_product_step_price.month_order_sum
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    public void setMonthOrderSum(Integer monthOrderSum) {
        this.monthOrderSum = monthOrderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_step_price.price
     *
     * @return the value of t_product_step_price.price
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_step_price.price
     *
     * @param price the value for t_product_step_price.price
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_step_price.type
     *
     * @return the value of t_product_step_price.type
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_step_price.type
     *
     * @param type the value for t_product_step_price.type
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_step_price.create_at
     *
     * @return the value of t_product_step_price.create_at
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_step_price.create_at
     *
     * @param createAt the value for t_product_step_price.create_at
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_step_price.update_at
     *
     * @return the value of t_product_step_price.update_at
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_step_price.update_at
     *
     * @param updateAt the value for t_product_step_price.update_at
     *
     * @mbg.generated Tue Jun 05 17:08:57 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}