package com.doushabao.mappers;

import com.doushabao.entity.TSysBill;
import com.doushabao.entity.TSysBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSysBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_bill
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    long countByExample(TSysBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_bill
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    int deleteByExample(TSysBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_bill
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_bill
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    int insert(TSysBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_bill
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    int insertSelective(TSysBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_bill
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    List<TSysBill> selectByExample(TSysBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_bill
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    TSysBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_bill
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") TSysBill record, @Param("example") TSysBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_bill
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    int updateByExample(@Param("record") TSysBill record, @Param("example") TSysBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_bill
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    int updateByPrimaryKeySelective(TSysBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_bill
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    int updateByPrimaryKey(TSysBill record);
}