package com.doushabao.saas.mapper.order;

import com.doushabao.saas.pojo.order.OrderBillLog;
import com.doushabao.saas.pojo.order.OrderBillLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderBillLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_bill_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    long countByExample(OrderBillLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_bill_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int deleteByExample(OrderBillLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_bill_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_bill_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int insert(OrderBillLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_bill_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int insertSelective(OrderBillLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_bill_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    List<OrderBillLog> selectByExample(OrderBillLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_bill_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    OrderBillLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_bill_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderBillLog record, @Param("example") OrderBillLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_bill_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int updateByExample(@Param("record") OrderBillLog record, @Param("example") OrderBillLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_bill_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int updateByPrimaryKeySelective(OrderBillLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_bill_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int updateByPrimaryKey(OrderBillLog record);
}