package com.doushabao.saas.mapper.order;

import com.doushabao.saas.pojo.order.OrderProduct;
import com.doushabao.saas.pojo.order.OrderProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    long countByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int deleteByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int insert(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int insertSelective(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    List<OrderProduct> selectByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    OrderProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderProduct record, @Param("example") OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int updateByExample(@Param("record") OrderProduct record, @Param("example") OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int updateByPrimaryKeySelective(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int updateByPrimaryKey(OrderProduct record);
}