package com.doushabao.saas.mapper.order;

import com.doushabao.saas.pojo.order.WxPayLog;
import com.doushabao.saas.pojo.order.WxPayLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxPayLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_pay_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    long countByExample(WxPayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_pay_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int deleteByExample(WxPayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_pay_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_pay_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int insert(WxPayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_pay_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int insertSelective(WxPayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_pay_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    List<WxPayLog> selectByExample(WxPayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_pay_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    WxPayLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_pay_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxPayLog record, @Param("example") WxPayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_pay_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int updateByExample(@Param("record") WxPayLog record, @Param("example") WxPayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_pay_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int updateByPrimaryKeySelective(WxPayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_pay_log
     *
     * @mbg.generated Mon Jun 04 11:04:34 CST 2018
     */
    int updateByPrimaryKey(WxPayLog record);
}