package com.doushabao.saas.mapper.company;

import com.doushabao.saas.pojo.company.CompanyExtendType;
import com.doushabao.saas.pojo.company.CompanyExtendTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyExtendTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_extend_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    long countByExample(CompanyExtendTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_extend_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    int deleteByExample(CompanyExtendTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_extend_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_extend_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    int insert(CompanyExtendType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_extend_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    int insertSelective(CompanyExtendType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_extend_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    List<CompanyExtendType> selectByExample(CompanyExtendTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_extend_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    CompanyExtendType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_extend_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") CompanyExtendType record, @Param("example") CompanyExtendTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_extend_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    int updateByExample(@Param("record") CompanyExtendType record, @Param("example") CompanyExtendTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_extend_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    int updateByPrimaryKeySelective(CompanyExtendType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_extend_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    int updateByPrimaryKey(CompanyExtendType record);
}