package com.doushabao.saas.mapper.company;

import com.doushabao.saas.pojo.company.CompanyProduct;
import com.doushabao.saas.pojo.company.CompanyProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_product
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    long countByExample(CompanyProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_product
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    int deleteByExample(CompanyProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_product
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_product
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    int insert(CompanyProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_product
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    int insertSelective(CompanyProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_product
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    List<CompanyProduct> selectByExample(CompanyProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_product
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    CompanyProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_product
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") CompanyProduct record, @Param("example") CompanyProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_product
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    int updateByExample(@Param("record") CompanyProduct record, @Param("example") CompanyProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_product
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    int updateByPrimaryKeySelective(CompanyProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_product
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    int updateByPrimaryKey(CompanyProduct record);
}