package com.doushabao.saas.mapper.company;

import com.doushabao.saas.pojo.company.SyncUserLog;
import com.doushabao.saas.pojo.company.SyncUserLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SyncUserLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_user_log
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    long countByExample(SyncUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_user_log
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    int deleteByExample(SyncUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_user_log
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_user_log
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    int insert(SyncUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_user_log
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    int insertSelective(SyncUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_user_log
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    List<SyncUserLog> selectByExample(SyncUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_user_log
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    SyncUserLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_user_log
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") SyncUserLog record, @Param("example") SyncUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_user_log
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    int updateByExample(@Param("record") SyncUserLog record, @Param("example") SyncUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_user_log
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    int updateByPrimaryKeySelective(SyncUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sync_user_log
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    int updateByPrimaryKey(SyncUserLog record);
}