package com.doushabao.entity;

import java.util.Date;

public class TSysBill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_bill.id
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_bill.source
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_bill.company_name
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_bill.ticket_no
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    private String ticketNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_bill.start_time
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_bill.end_time
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_bill.add_time
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_bill.update_time
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_bill.pay_time
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_bill.origin_amount
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    private Integer originAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_bill.discount_amount
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    private Integer discountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_bill.amount
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_bill.status
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_bill.message
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_bill.id
     *
     * @return the value of t_sys_bill.id
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_bill.id
     *
     * @param id the value for t_sys_bill.id
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_bill.source
     *
     * @return the value of t_sys_bill.source
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_bill.source
     *
     * @param source the value for t_sys_bill.source
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_bill.company_name
     *
     * @return the value of t_sys_bill.company_name
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_bill.company_name
     *
     * @param companyName the value for t_sys_bill.company_name
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_bill.ticket_no
     *
     * @return the value of t_sys_bill.ticket_no
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public String getTicketNo() {
        return ticketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_bill.ticket_no
     *
     * @param ticketNo the value for t_sys_bill.ticket_no
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public void setTicketNo(String ticketNo) {
        this.ticketNo = ticketNo == null ? null : ticketNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_bill.start_time
     *
     * @return the value of t_sys_bill.start_time
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_bill.start_time
     *
     * @param startTime the value for t_sys_bill.start_time
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_bill.end_time
     *
     * @return the value of t_sys_bill.end_time
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_bill.end_time
     *
     * @param endTime the value for t_sys_bill.end_time
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_bill.add_time
     *
     * @return the value of t_sys_bill.add_time
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_bill.add_time
     *
     * @param addTime the value for t_sys_bill.add_time
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_bill.update_time
     *
     * @return the value of t_sys_bill.update_time
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_bill.update_time
     *
     * @param updateTime the value for t_sys_bill.update_time
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_bill.pay_time
     *
     * @return the value of t_sys_bill.pay_time
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_bill.pay_time
     *
     * @param payTime the value for t_sys_bill.pay_time
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_bill.origin_amount
     *
     * @return the value of t_sys_bill.origin_amount
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public Integer getOriginAmount() {
        return originAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_bill.origin_amount
     *
     * @param originAmount the value for t_sys_bill.origin_amount
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public void setOriginAmount(Integer originAmount) {
        this.originAmount = originAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_bill.discount_amount
     *
     * @return the value of t_sys_bill.discount_amount
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public Integer getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_bill.discount_amount
     *
     * @param discountAmount the value for t_sys_bill.discount_amount
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public void setDiscountAmount(Integer discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_bill.amount
     *
     * @return the value of t_sys_bill.amount
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_bill.amount
     *
     * @param amount the value for t_sys_bill.amount
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_bill.status
     *
     * @return the value of t_sys_bill.status
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_bill.status
     *
     * @param status the value for t_sys_bill.status
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_bill.message
     *
     * @return the value of t_sys_bill.message
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_bill.message
     *
     * @param message the value for t_sys_bill.message
     *
     * @mbg.generated Tue May 29 22:46:00 CST 2018
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}