package com.doushabao.saas.pojo.company;

import java.math.BigDecimal;
import java.util.Date;

public class CompanyProduct {

    //该商户合作
    public static final Integer IS_USE = 1;
    //该商户不合作
    public static final Integer UN_USE = 0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.id
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.source
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.product_id
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.add_time
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.status
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.adjust_warn
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private Integer adjustWarn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.is_adjust
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private Integer isAdjust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.f1
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private BigDecimal f1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.f2
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private BigDecimal f2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.f3
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private BigDecimal f3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.f4
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private BigDecimal f4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.factor
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private BigDecimal factor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.warn_time
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private Date warnTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.adjust_time
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private Date adjustTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.create_at
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_product.update_at
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.id
     *
     * @return the value of t_company_product.id
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.id
     *
     * @param id the value for t_company_product.id
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.source
     *
     * @return the value of t_company_product.source
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.source
     *
     * @param source the value for t_company_product.source
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.product_id
     *
     * @return the value of t_company_product.product_id
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.product_id
     *
     * @param productId the value for t_company_product.product_id
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.add_time
     *
     * @return the value of t_company_product.add_time
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.add_time
     *
     * @param addTime the value for t_company_product.add_time
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.status
     *
     * @return the value of t_company_product.status
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.status
     *
     * @param status the value for t_company_product.status
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.adjust_warn
     *
     * @return the value of t_company_product.adjust_warn
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public Integer getAdjustWarn() {
        return adjustWarn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.adjust_warn
     *
     * @param adjustWarn the value for t_company_product.adjust_warn
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setAdjustWarn(Integer adjustWarn) {
        this.adjustWarn = adjustWarn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.is_adjust
     *
     * @return the value of t_company_product.is_adjust
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public Integer getIsAdjust() {
        return isAdjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.is_adjust
     *
     * @param isAdjust the value for t_company_product.is_adjust
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setIsAdjust(Integer isAdjust) {
        this.isAdjust = isAdjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.f1
     *
     * @return the value of t_company_product.f1
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public BigDecimal getF1() {
        return f1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.f1
     *
     * @param f1 the value for t_company_product.f1
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setF1(BigDecimal f1) {
        this.f1 = f1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.f2
     *
     * @return the value of t_company_product.f2
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public BigDecimal getF2() {
        return f2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.f2
     *
     * @param f2 the value for t_company_product.f2
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setF2(BigDecimal f2) {
        this.f2 = f2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.f3
     *
     * @return the value of t_company_product.f3
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public BigDecimal getF3() {
        return f3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.f3
     *
     * @param f3 the value for t_company_product.f3
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setF3(BigDecimal f3) {
        this.f3 = f3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.f4
     *
     * @return the value of t_company_product.f4
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public BigDecimal getF4() {
        return f4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.f4
     *
     * @param f4 the value for t_company_product.f4
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setF4(BigDecimal f4) {
        this.f4 = f4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.factor
     *
     * @return the value of t_company_product.factor
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public BigDecimal getFactor() {
        return factor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.factor
     *
     * @param factor the value for t_company_product.factor
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setFactor(BigDecimal factor) {
        this.factor = factor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.warn_time
     *
     * @return the value of t_company_product.warn_time
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public Date getWarnTime() {
        return warnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.warn_time
     *
     * @param warnTime the value for t_company_product.warn_time
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setWarnTime(Date warnTime) {
        this.warnTime = warnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.adjust_time
     *
     * @return the value of t_company_product.adjust_time
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public Date getAdjustTime() {
        return adjustTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.adjust_time
     *
     * @param adjustTime the value for t_company_product.adjust_time
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setAdjustTime(Date adjustTime) {
        this.adjustTime = adjustTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.create_at
     *
     * @return the value of t_company_product.create_at
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.create_at
     *
     * @param createAt the value for t_company_product.create_at
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_product.update_at
     *
     * @return the value of t_company_product.update_at
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_product.update_at
     *
     * @param updateAt the value for t_company_product.update_at
     *
     * @mbg.generated Mon Jun 11 16:46:04 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}