package com.doushabao.saas.pojo.company;

import java.util.Date;

public class CompanyExtendType {

    //进口
    public static final Integer IMPORT = 0;

    //出口
    public static final Integer EXPORT = 1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_extend_type.id
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_extend_type.source
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_extend_type.trade_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    private Integer tradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_extend_type.company_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    private Integer companyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_extend_type.status
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_extend_type.create_at
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_extend_type.update_at
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_extend_type.id
     *
     * @return the value of t_company_extend_type.id
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_extend_type.id
     *
     * @param id the value for t_company_extend_type.id
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_extend_type.source
     *
     * @return the value of t_company_extend_type.source
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_extend_type.source
     *
     * @param source the value for t_company_extend_type.source
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_extend_type.trade_type
     *
     * @return the value of t_company_extend_type.trade_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    public Integer getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_extend_type.trade_type
     *
     * @param tradeType the value for t_company_extend_type.trade_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    public void setTradeType(Integer tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_extend_type.company_type
     *
     * @return the value of t_company_extend_type.company_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    public Integer getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_extend_type.company_type
     *
     * @param companyType the value for t_company_extend_type.company_type
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    public void setCompanyType(Integer companyType) {
        this.companyType = companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_extend_type.status
     *
     * @return the value of t_company_extend_type.status
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_extend_type.status
     *
     * @param status the value for t_company_extend_type.status
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_extend_type.create_at
     *
     * @return the value of t_company_extend_type.create_at
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_extend_type.create_at
     *
     * @param createAt the value for t_company_extend_type.create_at
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_extend_type.update_at
     *
     * @return the value of t_company_extend_type.update_at
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_extend_type.update_at
     *
     * @param updateAt the value for t_company_extend_type.update_at
     *
     * @mbg.generated Wed Jun 13 11:16:54 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}