package com.doushabao.saas.pojo.company;

import java.util.Date;

public class Company {

    //基本信息完成
    public static final Integer IS_COMPLETE = 1;

    //基本信息未完成
    public static final Integer UN_COMPLETE = 0;

    //该商户可用
    public static final Integer IS_USE = 1;

    //该商户不可用
    public static final Integer UN_USE = 0;

    //该商户进口
    public static final Integer IS_IMPORT = 1;

    //该商户不是进口
    public static final Integer UN_IMPORT = 0;

    //该商户出口
    public static final Integer IS_EXPORT = 1;

    //该商户不是出口
    public static final Integer UN_EXPORT = 0;

    //从何处得知豆沙包 0 无从得知
    public static final Integer UN_KNOW = 0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.id
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.source
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.company_name
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.status
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.company_rank
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private Integer companyRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.company_key
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String companyKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.user_id
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.is_complete
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private Integer isComplete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.is_import
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private Integer isImport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.is_export
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private Integer isExport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.contact_name
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.contact_phone
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.email
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.add_time
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.update_time
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.company_license
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String companyLicense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.license_img_url
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String licenseImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.company_country
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String companyCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.company_address
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String companyAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.company_site
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String companySite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.company_scope
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String companyScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.main_line
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String mainLine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.business_name
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private Integer businessName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.business_phone
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String businessPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.business_email
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String businessEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.business_wx
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String businessWx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.qr_code
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String qrCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.hear_dsb
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private Integer hearDsb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.business_refer
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String businessRefer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.agreement_start_time
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private Date agreementStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.agreement_end_time
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private Date agreementEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.e_points
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String ePoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.e_chain
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private String eChain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.create_at
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.update_at
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.id
     *
     * @return the value of t_company.id
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.id
     *
     * @param id the value for t_company.id
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.source
     *
     * @return the value of t_company.source
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.source
     *
     * @param source the value for t_company.source
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.company_name
     *
     * @return the value of t_company.company_name
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.company_name
     *
     * @param companyName the value for t_company.company_name
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.status
     *
     * @return the value of t_company.status
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.status
     *
     * @param status the value for t_company.status
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.company_rank
     *
     * @return the value of t_company.company_rank
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public Integer getCompanyRank() {
        return companyRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.company_rank
     *
     * @param companyRank the value for t_company.company_rank
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setCompanyRank(Integer companyRank) {
        this.companyRank = companyRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.company_key
     *
     * @return the value of t_company.company_key
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getCompanyKey() {
        return companyKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.company_key
     *
     * @param companyKey the value for t_company.company_key
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setCompanyKey(String companyKey) {
        this.companyKey = companyKey == null ? null : companyKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.user_id
     *
     * @return the value of t_company.user_id
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.user_id
     *
     * @param userId the value for t_company.user_id
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.is_complete
     *
     * @return the value of t_company.is_complete
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public Integer getIsComplete() {
        return isComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.is_complete
     *
     * @param isComplete the value for t_company.is_complete
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setIsComplete(Integer isComplete) {
        this.isComplete = isComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.is_import
     *
     * @return the value of t_company.is_import
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public Integer getIsImport() {
        return isImport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.is_import
     *
     * @param isImport the value for t_company.is_import
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setIsImport(Integer isImport) {
        this.isImport = isImport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.is_export
     *
     * @return the value of t_company.is_export
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public Integer getIsExport() {
        return isExport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.is_export
     *
     * @param isExport the value for t_company.is_export
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setIsExport(Integer isExport) {
        this.isExport = isExport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.contact_name
     *
     * @return the value of t_company.contact_name
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.contact_name
     *
     * @param contactName the value for t_company.contact_name
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.contact_phone
     *
     * @return the value of t_company.contact_phone
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.contact_phone
     *
     * @param contactPhone the value for t_company.contact_phone
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.email
     *
     * @return the value of t_company.email
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.email
     *
     * @param email the value for t_company.email
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.add_time
     *
     * @return the value of t_company.add_time
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.add_time
     *
     * @param addTime the value for t_company.add_time
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.update_time
     *
     * @return the value of t_company.update_time
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.update_time
     *
     * @param updateTime the value for t_company.update_time
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.company_license
     *
     * @return the value of t_company.company_license
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getCompanyLicense() {
        return companyLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.company_license
     *
     * @param companyLicense the value for t_company.company_license
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setCompanyLicense(String companyLicense) {
        this.companyLicense = companyLicense == null ? null : companyLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.license_img_url
     *
     * @return the value of t_company.license_img_url
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getLicenseImgUrl() {
        return licenseImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.license_img_url
     *
     * @param licenseImgUrl the value for t_company.license_img_url
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setLicenseImgUrl(String licenseImgUrl) {
        this.licenseImgUrl = licenseImgUrl == null ? null : licenseImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.company_country
     *
     * @return the value of t_company.company_country
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getCompanyCountry() {
        return companyCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.company_country
     *
     * @param companyCountry the value for t_company.company_country
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setCompanyCountry(String companyCountry) {
        this.companyCountry = companyCountry == null ? null : companyCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.company_address
     *
     * @return the value of t_company.company_address
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.company_address
     *
     * @param companyAddress the value for t_company.company_address
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.company_site
     *
     * @return the value of t_company.company_site
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getCompanySite() {
        return companySite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.company_site
     *
     * @param companySite the value for t_company.company_site
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setCompanySite(String companySite) {
        this.companySite = companySite == null ? null : companySite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.company_scope
     *
     * @return the value of t_company.company_scope
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getCompanyScope() {
        return companyScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.company_scope
     *
     * @param companyScope the value for t_company.company_scope
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setCompanyScope(String companyScope) {
        this.companyScope = companyScope == null ? null : companyScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.main_line
     *
     * @return the value of t_company.main_line
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getMainLine() {
        return mainLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.main_line
     *
     * @param mainLine the value for t_company.main_line
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setMainLine(String mainLine) {
        this.mainLine = mainLine == null ? null : mainLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.business_name
     *
     * @return the value of t_company.business_name
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public Integer getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.business_name
     *
     * @param businessName the value for t_company.business_name
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setBusinessName(Integer businessName) {
        this.businessName = businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.business_phone
     *
     * @return the value of t_company.business_phone
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getBusinessPhone() {
        return businessPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.business_phone
     *
     * @param businessPhone the value for t_company.business_phone
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setBusinessPhone(String businessPhone) {
        this.businessPhone = businessPhone == null ? null : businessPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.business_email
     *
     * @return the value of t_company.business_email
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getBusinessEmail() {
        return businessEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.business_email
     *
     * @param businessEmail the value for t_company.business_email
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setBusinessEmail(String businessEmail) {
        this.businessEmail = businessEmail == null ? null : businessEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.business_wx
     *
     * @return the value of t_company.business_wx
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getBusinessWx() {
        return businessWx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.business_wx
     *
     * @param businessWx the value for t_company.business_wx
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setBusinessWx(String businessWx) {
        this.businessWx = businessWx == null ? null : businessWx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.qr_code
     *
     * @return the value of t_company.qr_code
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getQrCode() {
        return qrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.qr_code
     *
     * @param qrCode the value for t_company.qr_code
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setQrCode(String qrCode) {
        this.qrCode = qrCode == null ? null : qrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.hear_dsb
     *
     * @return the value of t_company.hear_dsb
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public Integer getHearDsb() {
        return hearDsb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.hear_dsb
     *
     * @param hearDsb the value for t_company.hear_dsb
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setHearDsb(Integer hearDsb) {
        this.hearDsb = hearDsb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.business_refer
     *
     * @return the value of t_company.business_refer
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getBusinessRefer() {
        return businessRefer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.business_refer
     *
     * @param businessRefer the value for t_company.business_refer
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setBusinessRefer(String businessRefer) {
        this.businessRefer = businessRefer == null ? null : businessRefer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.agreement_start_time
     *
     * @return the value of t_company.agreement_start_time
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public Date getAgreementStartTime() {
        return agreementStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.agreement_start_time
     *
     * @param agreementStartTime the value for t_company.agreement_start_time
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setAgreementStartTime(Date agreementStartTime) {
        this.agreementStartTime = agreementStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.agreement_end_time
     *
     * @return the value of t_company.agreement_end_time
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public Date getAgreementEndTime() {
        return agreementEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.agreement_end_time
     *
     * @param agreementEndTime the value for t_company.agreement_end_time
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setAgreementEndTime(Date agreementEndTime) {
        this.agreementEndTime = agreementEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.e_points
     *
     * @return the value of t_company.e_points
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String getePoints() {
        return ePoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.e_points
     *
     * @param ePoints the value for t_company.e_points
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setePoints(String ePoints) {
        this.ePoints = ePoints == null ? null : ePoints.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.e_chain
     *
     * @return the value of t_company.e_chain
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public String geteChain() {
        return eChain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.e_chain
     *
     * @param eChain the value for t_company.e_chain
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void seteChain(String eChain) {
        this.eChain = eChain == null ? null : eChain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.create_at
     *
     * @return the value of t_company.create_at
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.create_at
     *
     * @param createAt the value for t_company.create_at
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.update_at
     *
     * @return the value of t_company.update_at
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.update_at
     *
     * @param updateAt the value for t_company.update_at
     *
     * @mbg.generated Thu Jun 14 10:50:04 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}