package com.doushabao.saas.pojo.company;

public class SyncUserLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_user_log.id
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_user_log.phone_no
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_user_log.name
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_user_log.merchant_code
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    private String merchantCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_user_log.merchant_name
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    private String merchantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_user_log.message
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sync_user_log.code
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_user_log.id
     *
     * @return the value of t_sync_user_log.id
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_user_log.id
     *
     * @param id the value for t_sync_user_log.id
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_user_log.phone_no
     *
     * @return the value of t_sync_user_log.phone_no
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_user_log.phone_no
     *
     * @param phoneNo the value for t_sync_user_log.phone_no
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_user_log.name
     *
     * @return the value of t_sync_user_log.name
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_user_log.name
     *
     * @param name the value for t_sync_user_log.name
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_user_log.merchant_code
     *
     * @return the value of t_sync_user_log.merchant_code
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    public String getMerchantCode() {
        return merchantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_user_log.merchant_code
     *
     * @param merchantCode the value for t_sync_user_log.merchant_code
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode == null ? null : merchantCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_user_log.merchant_name
     *
     * @return the value of t_sync_user_log.merchant_name
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_user_log.merchant_name
     *
     * @param merchantName the value for t_sync_user_log.merchant_name
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_user_log.message
     *
     * @return the value of t_sync_user_log.message
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_user_log.message
     *
     * @param message the value for t_sync_user_log.message
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sync_user_log.code
     *
     * @return the value of t_sync_user_log.code
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sync_user_log.code
     *
     * @param code the value for t_sync_user_log.code
     *
     * @mbg.generated Sat Jun 16 18:06:50 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}